name: Build and Push Backend Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # Building image for client portal
          docker build -t kaveengayanga12/eventslk-client-portal:${{ github.sha }} .
          docker push kaveengayanga12/eventslk-client-portal:${{ github.sha }}

      - name: Update K8s Manifests
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/EventsLK/eventslk-k8s-manifests.git
          cd eventslk-k8s-manifests
          # Updating the client portal deployment file
          sed -i "s|image: kaveengayanga12/eventslk-client-portal:.*|image: kaveengayanga12/eventslk-client-portal:${{ github.sha }}|" k8s/client-portal-deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update client portal image to ${{ github.sha }}"
          git push origin main